app.port=9999
app.permissions=1
antenna.sftp.user=0//uwQQrgSgFkC5mIOkQ5A==
antenna.sftp.password=M9qXWC4gjmbGR4RVWGFj5Q==
antenna.sftp.port=22
antenna.sftp.upload.path=/home/root/
antenna.param.RollFactor.compensation=1
antenna.heartbeat=1
antenna.heartbeat.timeout=2000